documentation(ES-838764-SalesForce): Add salesforce integration topic in schedule docs.
syncfusion-content/ej2-schedule-docs pull request #16
Opened 2023-07-31 05:10 UTC by vijayravi161099

Description:
Integrate salesforce topic in latest version 22.2.5.

Areas affected and ensured:
All possible cases

Test cases:
NA

Test bed sample location:
NA

Additional checklist
Did you run the automation against your fix? NA
Is there any API name change? No
Is there any existing behavior change of other features due to this code change? No
Does your new code introduce new warnings or binding errors? No
Does your code pass all FxCop and StyleCop rules? NA
Did you record this case in the unit test or UI test? No

2023-07-31 05:11 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-838764-SalesForce](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/12/console)**

2023-07-31 05:12 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-838764-SalesForce](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/12/console)**

2023-07-31 05:13 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-838764-SalesForce](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/12/)<br/>**

2023-07-31 05:49 UTC, maheshtps requested changes

2023-07-31 05:49 UTC, maheshtps commented on ej2-javascript/schedule/data-binding.md
> +### Summary
1. Move this topic to how-to, and add in see also of data binding
2. remove unwanted headings like intro, summary
3. add respective images

2023-07-31 07:12 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-838764-SalesForce](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/13/console)**

2023-07-31 07:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-838764-SalesForce](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/13/console)**

2023-07-31 07:17 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-838764-SalesForce](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/13/)<br/>**

2023-07-31 07:32 UTC, VengateshManiraj approved these changes

2023-07-31 08:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-838764-SalesForce](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/14/console)**

2023-07-31 08:08 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-838764-SalesForce](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/14/)<br/>**

2023-08-02 14:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-838764-SalesForce](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/16/)<br/>**

2023-08-10 11:27 UTC, closed without merging