docs(ES-845513): Include UG for editor header and footer.
syncfusion-content/ej2-schedule-docs pull request #37
Opened 2023-09-12 13:00 UTC by AshokkumarKaruppasamy

Include UG for editor header and footer.

2023-09-12 13:01 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/42/)<br/>**

2023-09-13 05:42 UTC, VengateshManiraj requested changes

2023-09-13 05:42 UTC, VengateshManiraj commented on ej2-javascript/schedule/editor-template.md
> +## Customizing event header using template
Customizing editor window header and footer using template

2023-09-13 06:10 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/43/)<br/>**

2023-09-13 06:20 UTC, VengateshManiraj requested changes

2023-09-13 06:20 UTC, VengateshManiraj commented on ej2-javascript/schedule/editor-template.md
> +## Customizing editor window header and footer using template
How to customize header and footer using template

2023-09-13 06:20 UTC, VengateshManiraj commented on ej2-javascript/schedule/editor-template.md
> +The editor custom header can be customized by using the `editorHeaderTemplate` option, and editor window footer can be customized footer by making use of the `editorFooterTemplate` option. In this sc
The editor window's header and footer can be enhanced with custom designs using the `editorHeaderTemplate` and `editorFooterTemplate` options. To achieve this, create a script template that includes the necessary fields. Ensure that the template type is set to `text/x-template`.

2023-09-13 06:20 UTC, VengateshManiraj commented on ej2-javascript/code-snippet/schedule/editor-header-footer-cs1/index.ts
> +    showQuickInfo: false,
why showQuickInfo set as false

2023-09-13 06:20 UTC, VengateshManiraj commented on ej2-javascript/schedule/editor-template.md
> +In this demo, the editor custom header is customized based on the appointment subject field which can be achieved by the `editorHeaderTemplate`.Additionally, the `editorFooterTemplate` is employed to
In this demo, we customize the editor's header based on the appointment's subject field using the `editorHeaderTemplate`. Additionally, we utilize the `editorFooterTemplate` to manage the functionality for saving, deleting, and canceling actions.

2023-09-13 06:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/44/)<br/>**

2023-09-13 06:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/45/)<br/>**

2023-09-13 06:40 UTC, AshokkumarKaruppasamy commented on ej2-javascript/schedule/editor-template.md
> +## Customizing editor window header and footer using template
changed the header ange updated

2023-09-13 06:41 UTC, AshokkumarKaruppasamy commented on ej2-javascript/schedule/editor-template.md
> +The editor custom header can be customized by using the `editorHeaderTemplate` option, and editor window footer can be customized footer by making use of the `editorFooterTemplate` option. In this sc
changed the content

2023-09-13 06:41 UTC, AshokkumarKaruppasamy commented on ej2-javascript/code-snippet/schedule/editor-header-footer-cs1/index.ts
> +    showQuickInfo: false,
Addressed the corrections and changes updated

2023-09-13 06:42 UTC, AshokkumarKaruppasamy commented on ej2-javascript/schedule/editor-template.md
> +In this demo, the editor custom header is customized based on the appointment subject field which can be achieved by the `editorHeaderTemplate`.Additionally, the `editorFooterTemplate` is employed to
changed the content

2023-09-13 06:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/46/)<br/>**

2023-09-13 11:33 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/47/)<br/>**

2023-09-13 11:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/48/)<br/>**

2023-09-14 04:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/49/console)**

2023-09-14 04:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/49/)<br/>**

2023-09-14 04:26 UTC, VengateshManiraj requested changes

2023-09-14 04:26 UTC, VengateshManiraj commented on ej2-javascript/code-snippet/schedule/editor-header-footer-cs1/js/index.html
> +        <label id="text">Verify</label>
Verified

2023-09-14 04:26 UTC, VengateshManiraj commented on ej2-javascript/schedule/editor-template.md
> +In this demo, we customize the editor's header based on the appointment's subject field using the `editorHeaderTemplate`. Additionally, we utilize the `editorFooterTemplate` to manage the functionali
In this demo, we tailor the editor's header according to the appointment's subject field using the `editorHeaderTemplate`. Furthermore, we make use of the `editorFooterTemplate` to handle the functionality of validating specific fields before proceeding with the save action or canceling it if validation requirements are not met.

2023-09-14 04:38 UTC, AshokkumarKaruppasamy commented on ej2-javascript/code-snippet/schedule/editor-header-footer-cs1/js/index.html
> +        <label id="text">Verify</label>
changed

2023-09-14 04:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/50/)<br/>**

2023-09-14 04:40 UTC, AshokkumarKaruppasamy commented on ej2-javascript/schedule/editor-template.md
> +In this demo, we customize the editor's header based on the appointment's subject field using the `editorHeaderTemplate`. Additionally, we utilize the `editorFooterTemplate` to manage the functionali
I've modified the content and made updates.

2023-09-14 04:41 UTC, VengateshManiraj approved these changes

2023-09-14 05:21 UTC, maheshtps requested changes

2023-09-14 05:21 UTC, maheshtps commented on ej2-javascript/code-snippet/schedule/editor-header-footer-cs1/js/index.html
> +    <script src="https://cdn.syncfusion.com/ej2/20.4.38/dist/ej2.min.js" type="text/javascript"></script>
use the latest versions to avail this feature

2023-09-14 07:30 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/51/console)**

2023-09-14 07:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/51/)<br/>**

2023-09-14 07:33 UTC, AshokkumarKaruppasamy commented on ej2-javascript/code-snippet/schedule/editor-header-footer-cs1/js/index.html
> +    <script src="https://cdn.syncfusion.com/ej2/20.4.38/dist/ej2.min.js" type="text/javascript"></script>
i have addressed the review corrections and  changes updated

2023-09-14 07:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/53/)<br/>**

2023-09-14 09:33 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/55/)<br/>**

2023-09-14 09:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/56/)<br/>**

2023-09-14 09:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/57/console)**

2023-09-14 09:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-845513-editorTemplates](https://jenkins.syncfusion.com/job/Content/job/ej2-schedule-docs/57/)<br/>**

2023-09-14 09:57 UTC, VengateshManiraj approved these changes

2023-09-14 09:58 UTC, maheshtps approved these changes

2023-09-14 09:58 UTC, merged